hack_me_please: true
log_debug: true

server:
  http:
      listen_addr: ":8123"
      allowed_networks: ["127.0.0.0/24"]

users:
  - name: "default"
    to_cluster: "default"
    to_user: "default"

# by default each cluster has `default` user which can be overridden by section `users`
clusters:
  - name: "default"
    nodes: ["clickhouse:28123"]